steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-streamlit-app', '.']
  # Reemplaza 'gcr.io/$PROJECT_ID/my-streamlit-app' con el nombre completo de tu imagen
images: ['gcr.io/$PROJECT_ID/my-streamlit-app']